job = input("Name a dream job. >_")
animal = input("Name an animal. >_")
noun = input("Name a noun. >_")
Building_type = input("Name a living space. >_")
ing_word = input("Name a word that ends in ing. >_")
verb = input("Name a verb. >_")
verb2 = input("Name another verb. >_")
tool = input("Name a tool. >_")
ing_word2 = input("Name another word that ends in ing. >_")
adjective = input("Name an adjective. >_")

print("About a week ago, a %s had went out to feed his %s like any other day." % (job, animal))
print("He seen this strange %s but thought nothing of it." % noun)
print("He continued with his day feeding every animal at his %s." % Building_type)
print("He tried %s to get it out of the way since it might %s and %s his livestock." % (ing_word, verb, verb2))
print("He came out with his %s but he noticed a %s tint." % (tool, ing_word2))
print("He thought this was going to be his day, his time to get % and make it in the world." % adjective)